name: CI — Jest Tests Only

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Create minimal config for CI
        run: |
          cat <<EOF > config.json
          {
            "url": "http://localhost:4567",
            "secret": "ci-secret",
            "database": "redis",
            "redis": {
              "host": "127.0.0.1",
              "port": 6379
            }
          }
          EOF

      - name: Build NodeBB
        run: ./nodebb build

      - name: Run Tests
        run: npm test
